title: Albert Paul
email: albertpaulp(@)gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Hey there! I’m Albert, this is my personal blog. I usually write about technology, coding and politics. Contents are
  free to use unless stated otherwise.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://www.albertpaulp.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: albertpaulp
github_username:  albertpaulp

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jemoji
permalink: none
disqus:
  shortname: albertpaulp

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
